spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5432/book-ms
    username: postgres
    password: senh@BD
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true
    properties:
      hibernate.format_sql: true
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
      
  flyway:
    locations: classpath:migration
    baselineOnMigrate: true
    placeholderReplacement: true
    baselineVersion: 1
    encoding: UTF-8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka      
server:
  port: 8100
